spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 10000

app:
  auth:
    jwks-url: https://dev-dx4dfakl78fup4q2.us.auth0.com/.well-known/jwks.json